@startuml calendar.puml
class Calendar{
	+ int getYear()
	+ uint8_t dayNumber(uint8_t day, uint8_t month, int year)
	+ string getMonthName(uint8_t monthNumber)
	+ uint8_t numberOfDays(uint8_t monthNumber, int year)
	+ void printCalendarYear(int year)
	+ void calendar_init(char option)
}
@enduml