@startuml calendar.puml
class Calendar{
	+ int getYear()
	+ int dayNumber(int day, int month, int year)
	+ string getMonthName(int monthNumber)
	+ int numberOfDays(int monthNumber, int year)
	+ void printCalendarYear(int year)
	+ void calendar_init(char option)
}
@enduml