@startuml
class Timer
{

    - short minutes
    - short seconds
    - int totalTime

    + void timer_init(char option)
    + void infiniteTimer()
    + void stopWatch()
    + void countDownTimer()
}
@enduml